// Package enrollment implements one-time CSR enrollment and short-lived
// private-CA connector credentials. Private keys are generated by connectors;
// the control plane never receives or returns one.
package enrollment

import (
	"context"
	"crypto/rand"
	"crypto/sha256"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/hex"
	"encoding/pem"
	"errors"
	"math/big"
	"net/url"
	"os"
	"time"

	"github.com/dcolinmorgan/herdr-remote/internal/protocol"
	"github.com/dcolinmorgan/herdr-remote/internal/store"
)

type Service struct {
	store *store.Store
	ca    *x509.Certificate
	key   any
	now   func() time.Time
}

func Load(st *store.Store, certPath, keyPath string) (*Service, error) {
	certPEM, err := os.ReadFile(certPath)
	if err != nil {
		return nil, err
	}
	keyPEM, err := os.ReadFile(keyPath)
	if err != nil {
		return nil, err
	}
	cb, _ := pem.Decode(certPEM)
	kb, _ := pem.Decode(keyPEM)
	if cb == nil || kb == nil {
		return nil, errors.New("invalid CA PEM")
	}
	ca, err := x509.ParseCertificate(cb.Bytes)
	if err != nil {
		return nil, err
	}
	key, err := x509.ParsePKCS8PrivateKey(kb.Bytes)
	if err != nil {
		if k, err2 := x509.ParseECPrivateKey(kb.Bytes); err2 == nil {
			key = k
		} else {
			return nil, err
		}
	}
	return &Service{store: st, ca: ca, key: key, now: time.Now}, nil
}
func New(st *store.Store, ca *x509.Certificate, key any) *Service {
	return &Service{store: st, ca: ca, key: key, now: time.Now}
}

type Token struct {
	Token     string    `json:"token"`
	HostID    string    `json:"host_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (s *Service) CreateToken(ctx context.Context, display string) (Token, error) {
	host, err := protocol.NewUUIDv7()
	if err != nil {
		return Token{}, err
	}
	raw := make([]byte, 32)
	if _, err = rand.Read(raw); err != nil {
		return Token{}, err
	}
	token := hex.EncodeToString(raw)
	expires := s.now().UTC().Add(10 * time.Minute)
	if err = s.store.CreateEnrollment(ctx, store.HashToken(token), host, display, expires); err != nil {
		return Token{}, err
	}
	return Token{token, host, expires}, nil
}

type Certificate struct {
	HostID           string    `json:"host_id"`
	CertificatePEM   string    `json:"certificate_pem"`
	CACertificatePEM string    `json:"ca_certificate_pem"`
	NotAfter         time.Time `json:"not_after"`
}

func (s *Service) Enroll(ctx context.Context, token string, csrPEM []byte) (Certificate, error) {
	csr, err := parseCSR(csrPEM)
	if err != nil {
		return Certificate{}, err
	}
	tokenHash := store.HashToken(token)
	e, err := s.store.EnrollmentForToken(ctx, tokenHash)
	if err != nil {
		return Certificate{}, err
	}
	cert, record, err := s.issue(e.HostID, csr)
	if err != nil {
		return Certificate{}, err
	}
	if err = s.store.CommitEnrollmentCertificate(ctx, tokenHash, record); err != nil {
		return Certificate{}, err
	}
	return cert, nil
}
func (s *Service) Rotate(ctx context.Context, host string, csrPEM []byte) (Certificate, error) {
	csr, err := parseCSR(csrPEM)
	if err != nil {
		return Certificate{}, err
	}
	cert, record, err := s.issue(host, csr)
	if err != nil {
		return Certificate{}, err
	}
	if err = s.store.AddRotatedCertificate(ctx, record); err != nil {
		return Certificate{}, err
	}
	return cert, nil
}
func (s *Service) Revoke(ctx context.Context, host string) error {
	return s.store.RevokeHost(ctx, host)
}
func parseCSR(csrPEM []byte) (*x509.CertificateRequest, error) {
	b, _ := pem.Decode(csrPEM)
	if b == nil || b.Type != "CERTIFICATE REQUEST" {
		return nil, errors.New("invalid CSR PEM")
	}
	csr, err := x509.ParseCertificateRequest(b.Bytes)
	if err != nil || csr.CheckSignature() != nil {
		return nil, errors.New("invalid CSR signature")
	}
	if len(csr.DNSNames) > 0 || len(csr.EmailAddresses) > 0 || len(csr.IPAddresses) > 0 || len(csr.URIs) > 0 {
		return nil, errors.New("CSR identities are forbidden")
	}
	return csr, nil
}
func (s *Service) issue(host string, csr *x509.CertificateRequest) (Certificate, store.Certificate, error) {
	serialLimit := new(big.Int).Lsh(big.NewInt(1), 128)
	serial, err := rand.Int(rand.Reader, serialLimit)
	if err != nil {
		return Certificate{}, store.Certificate{}, err
	}
	now := s.now().UTC()
	uri, _ := url.Parse("spiffe://herdr/host/" + host)
	tpl := &x509.Certificate{SerialNumber: serial, Subject: pkix.Name{}, NotBefore: now.Add(-time.Minute), NotAfter: now.Add(30 * 24 * time.Hour), KeyUsage: x509.KeyUsageDigitalSignature, ExtKeyUsage: []x509.ExtKeyUsage{x509.ExtKeyUsageClientAuth}, URIs: []*url.URL{uri}, BasicConstraintsValid: true}
	der, err := x509.CreateCertificate(rand.Reader, tpl, s.ca, csr.PublicKey, s.key)
	if err != nil {
		return Certificate{}, store.Certificate{}, err
	}
	fp := sha256.Sum256(der)
	record := store.Certificate{Serial: serial.Text(16), HostID: host, Fingerprint: hex.EncodeToString(fp[:]), NotBefore: tpl.NotBefore, NotAfter: tpl.NotAfter}
	certPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der})
	caPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: s.ca.Raw})
	return Certificate{host, string(certPEM), string(caPEM), tpl.NotAfter}, record, nil
}
func Fingerprint(cert *x509.Certificate) string {
	h := sha256.Sum256(cert.Raw)
	return hex.EncodeToString(h[:])
}
