{ pkgs }:
pkgs.buildFHSEnv {
  name = "herdr-playwright-fhs";
  targetPkgs = pkgs: [
    pkgs.glib
    pkgs.nss
    pkgs.nspr
    pkgs.dbus
    pkgs.atk
    pkgs.at-spi2-atk
    pkgs.cups
    pkgs.expat
    pkgs.libdrm
    pkgs.libxkbcommon
    pkgs.mesa
    pkgs.libgbm
    pkgs.libglvnd
    pkgs.vulkan-loader
    pkgs.pango
    pkgs.cairo
    pkgs.alsa-lib
    pkgs.systemd
    pkgs.gtk4
    pkgs.gdk-pixbuf
    pkgs.harfbuzz
    pkgs.harfbuzzFull
    pkgs.graphene
    pkgs.icu74
    pkgs.libxml2
    pkgs.libxml2_13
    pkgs.sqlite
    pkgs.libxslt
    pkgs.lcms2
    pkgs.libevent
    pkgs.libopus
    pkgs.libgcrypt
    pkgs.libgpg-error
    pkgs.flite
    pkgs.libwebp
    pkgs.libavif
    pkgs.libepoxy
    pkgs.libjpeg
    pkgs.libpng
    pkgs.freetype
    pkgs.fontconfig
    pkgs.wayland
    pkgs.libmanette
    pkgs.enchant
    pkgs.libsecret
    pkgs.libpsl
    pkgs.nghttp2
    pkgs.woff2
    pkgs.hyphen
    pkgs.libtasn1
    pkgs.zlib
    pkgs.libjpeg8
    pkgs.x264
    pkgs.libx11
    pkgs.libxcb
    pkgs.libxcomposite
    pkgs.libxdamage
    pkgs.libxext
    pkgs.libxfixes
    pkgs.libxrandr
    pkgs.libxrender
    pkgs.libxtst
    pkgs.xorgserver
    pkgs.gst_all_1.gstreamer
    pkgs.gst_all_1.gst-plugins-base
    pkgs.gst_all_1.gst-plugins-good
    pkgs.gst_all_1.gst-plugins-bad
  ];
  extraBwrapArgs = [ "--bind /tmp /tmp" ];
  runScript = "bash";
}
